config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  get 'news/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root 'homes#index'
  resources :users
  resources :homes
  resources :news
  resources :articles,only: [:show]
  resources :bookmarks, only: [:index, :show, :create, :destroy]
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :bookmarks
    has_many :bookmarking_users, through: :bookmarks, source: :user
    belongs_to :user, optional: true
    validates :url,  :title, :description,
    presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find_by(article_id: params[:id])
    
    unless @article
      all_articles = fetch_articles_from_news_api
      @article = all_articles.find { |article| article["url"][/(\d+)(?!.*\d)/].to_i == params[:id].to_i }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/show.html.erb
<% if user_signed_in? %>
<div class="container mt-4">
 <div class="card">
   <% if @article && @article["urlToImage"].present? %>
     <%= image_tag @article["urlToImage"], class: "card-img-top" %>
   <% else %>
     <p>いらすとやの画像を挿入する</p>
   <% end %>
   <div class="card-body">
     <h5 class="card-title"><%= @article["title"] %></h5>
     <%= @article["description"] %>
     <a href="<%= @article["url"] %>" class="btn btn-primary">元の記事を読む</a>
   </div>
   <%= link_to "[ニュース一覧へ]", news_index_path %>

     <% article_id = @article["url"][/(\d+)(?!.*\d)/].to_i %>
     <% if current_user.bookmarked_articles.include?(article_id) %>
        <%= link_to 'ブックマーク削除', bookmark_path(bookmark), method: :delete, data: { confirm: 'このブックマークを削除しますか？' }, class: "btn btn-sm btn-outline-danger" %>
     <% else %>
        <%= link_to 'この記事をブックマーク登録する', bookmarks_path(article_id: article_id), method: :post %>
     <% end %>
 </div>
</div>

<% else %>
<div class="container mt-4">
 <div class="card">
   <% if @article && @article["urlToImage"].present? %>
     <%= image_tag @article["urlToImage"], class: "card-img-top" %>
   <% else %>
     <p>いらすとやの画像を挿入する</p>
   <% end %>
   <div class="card-body">
     <h5 class="card-title"><%= @article["title"] %></h5>
     <%= @article["description"] %>
   </div>
   <%= link_to "[ニュース一覧へ]", news_index_path %>
   
  </div>
</div>
<% end %>