config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  get 'news/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root 'homes#index'
  resources :users
  resources :homes
  resources :news
  resources :articles,only: [:show]
  resources :bookmarks, only: [:index, :show, :create, :destroy]
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  require "open-uri"
   
  def index
    @articles = fetch_articles_from_news_api
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<% if user_signed_in? %>
<header class="sticky-top bg-light">
    <p>Powered by <%= link_to "https://newsapi.org" do %> News API <% end %> </p>
    <p>現在の最新のニュースです（時刻を表示する）</p>
    <p>ユーザー名：<%= current_user.name %></p>
    <%= link_to "トップページに戻る", homes_index_path %>
</header>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @articles.each do |article| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <% if article["urlToImage"].present? %> <!-- APIのデータのキー名に合わせて修正が必要な場合あり -->
                <%= image_tag article["urlToImage"], :size =>'240x160' %>
            <% else %>
                <p>イラスト屋の画像を添付</p>
            <% end %>
            <div class="card-body">
              <p class="card-text">
                <%= article["title"] %>
              </p>
              <%= link_to "詳細ページへ", article_path(article["url"][/(\d+)(?!.*\d)/].to_i) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% else %>
<header class="sticky-top bg-light">
    <p>Powered by <%= link_to "https://newsapi.org" do %> News API <% end %> </p>
    <p>現在の最新のニュースです（時刻を表示する）</p>
    <p>ゲストさん</p>
    <%= link_to "トップページに戻る", homes_index_path %>
</header>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @articles.each do |article| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <% if article["urlToImage"].present? %>  
              <%= image_tag article["urlToImage"], :size =>'240x160' %>
            <% else %>
            <p>イラスト屋の画像を添付</p>
            <% end %>
            <div class="card-body">
              <p class="card-text">
                <%= article["title"] %>
              </p>
              <%= link_to "詳細ページへ", article_path(article["url"][/(\d+)(?!.*\d)/].to_i) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>